### ISSUE TITLE
vs code not working

### ISSUE THREAD

**Issue by Pranavpatil96k** [infinitepower18/CloneInVSCode-Safari#3]
install vs form app store contact
![Uploading Screenshot 2024-07-09 at 10.23.43 AM.png…]()
 apple and try chaing saffari extension and website with the help of apple. no issue from apple end so palese help me in this thank you

**Comment by infinitepower18** [comment]
Sorry I don't understand the problem you're facing. I can only provide support for the Clone in VS Code extension. Are you facing any issues with the extension?

**Comment by infinitepower18** [comment]
As I haven't heard from you I will be closing this issue. Let me know if you're experiencing any issues with the extension.
